The diameter of steel rods manufactured on two different machines A and B is
studied. Two random samples of sizes $n_1 = 12$ and $n_2 = 15$ are selected and the
sample means and sample standard deviations respectively are
1 x =24.6, s1 = 0.85
2 x =22.1, s2 = 0.98
Assuming that the diameters of the rods follow N ( μ1, σ1^2) and N ( μ2, σ22) and


a. Test for the equality of the variances.
b. Test the equality of means of the diameters of the rods manufactured by the
two machines assuming equal variances

## Testing for Equality of Variances and Means

### a. Testing for Equality of Variances

**Hypothesis:**

* **Null hypothesis (H0):** σ1² = σ2² (The variances are equal)
* **Alternative hypothesis (H1):** σ1² ≠ σ2² (The variances are not equal)

**Test statistic:**

* F = s1² / s2²

**Distribution:**

* F-distribution with degrees of freedom (n1 - 1) and (n2 - 1)

**Critical value:**

* Find the critical value from the F-distribution table using a significance level (α).

**Decision rule:**

* If F > Fα, reject H0.
* If F ≤ Fα, fail to reject H0.

**Calculation:**

* F = (0.85)² / (0.98)² ≈ 0.75

**Conclusion:**

* Compare the calculated F-value with the critical value. If the calculated value is greater than the critical value, reject the null hypothesis and conclude that the variances are not equal. Otherwise, fail to reject the null hypothesis and conclude that there is not enough evidence to suggest that the variances are different.

### b. Testing for Equality of Means (Assuming Equal Variances)

**Hypothesis:**

* **Null hypothesis (H0):** μ1 = μ2 (The means are equal)
* **Alternative hypothesis (H1):** μ1 ≠ μ2 (The means are not equal)

**Test statistic:**

* t = (x̄1 - x̄2) / (s_p * √(1/n1 + 1/n2))

* where s_p is the pooled standard deviation: s_p = √((n1 - 1)s1² + (n2 - 1)s2²) / (n1 + n2 - 2)

**Distribution:**

* t-distribution with degrees of freedom (n1 + n2 - 2)

**Critical value:**

* Find the critical value from the t-distribution table using a significance level (α).

**Decision rule:**

* If |t| > tα, reject H0.
* If |t| ≤ tα, fail to reject H0.

**Calculation:**

1. Calculate the pooled standard deviation: s_p = √(((12 - 1)(0.85)²) + ((15 - 1)(0.98)²) / (12 + 15 - 2))
2. Calculate the t-statistic: t = (24.6 - 22.1) / (s_p * √(1/12 + 1/15))

**Conclusion:**

* Compare the calculated |t| value with the critical value. If the calculated value is greater than the critical value, reject the null hypothesis and conclude that the means are not equal. Otherwise, fail to reject the null hypothesis and conclude that there is not enough evidence to suggest that the means are different.

**Note:** If the variances are found to be significantly different in part (a), a different test (e.g., Welch's t-test) should be used for testing the equality of means.

---------------------
## Constructing a 95% Confidence Interval for μ1 - μ2 (Assuming Equal Variances)

**Formula:**

* CI = (x̄1 - x̄2) ± tα/2 * s_p * √(1/n1 + 1/n2)

where:

* CI is the confidence interval
* x̄1 and x̄2 are the sample means
* tα/2 is the critical value from the t-distribution with degrees of freedom (n1 + n2 - 2) and a significance level of α/2
* s_p is the pooled standard deviation
* n1 and n2 are the sample sizes

**Calculation:**

1. **Find the critical value:** From the t-distribution table, find the t-value corresponding to a significance level of α/2 = 0.025 and degrees of freedom (12 + 15 - 2) = 25.

2. **Calculate the pooled standard deviation:** As calculated in the previous response, s_p = √(((12 - 1)(0.85)²) + ((15 - 1)(0.98)²) / (12 + 15 - 2))

3. **Calculate the confidence interval:** Substitute the values into the formula: CI = (24.6 - 22.1) ± tα/2 * s_p * √(1/12 + 1/15)

**Conclusion:**

* The resulting interval will be a range of values that is likely to contain the true difference between the population means μ1 and μ2 with a 95% probability.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% HEADER
\documentclass[a4paper,12pt]{article}
\usepackage{eurosym}
\usepackage{vmargin}
\usepackage{amsmath}
\usepackage{graphics}
\usepackage{epsfig}
\usepackage{enumerate}
\usepackage{multicol}
\usepackage{subfigure}
\usepackage{fancyhdr}
\usepackage{listings}
\usepackage{framed}
\usepackage{graphicx}
\usepackage{amsmath}
\usepackage{chngpage}
\usepackage{vmargin}
\setmargins{2.0cm}{2.5cm}{16 cm}{22cm}{0.5cm}{0cm}{1cm}{1cm}
\renewcommand{\baselinestretch}{1.3}
\setcounter{MaxMatrixCols}{10}

\begin{document}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\large 
\noindent The diameter of steel rods manufactured on two different machines A and B is
studied. Two random samples of sizes $n_1 = 12$ and $n_2 = 15$ are selected and the
sample means and sample standard deviations respectively are
1 x =24.6, s1 = 0.85
2 x =22.1, s2 = 0.98
Assuming that the diameters of the rods follow N ( μ1, σ1^2) and N ( μ2, σ22) and

\begin{enumerate}[(a)]
\item  Test for the equality of the variances.
\item  Test the equality of means of the diameters of the rods manufactured by the
two machines assuming σ
1
2 = σ
2
2
\item Construct 95\% confidence interval for μ
1 – μ2 assuming σ
1
2 = σ
2
2
\item  Construct 95\% confidence interval for σ
1
2 / σ
2
2[]
\end{enumerate}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\medskip
\noindent \textbf{Solution}


\noindent \textbf{Part (a)} 
a) 2
2
2
0 1 H :σ =σ s ν 2
2
2
1 1 H :σ ≠σ

\begin{itemize}
\item The test statistic is
0.7225
0.9604
2
1
2
= 2 =
s
F s =1.329
\item Critical value of F for (14,11) df at 5% level = 2.7316
\item Do not Reject H0.
b) H0 : μ
1 = μ
2 ; H1 : μ
1 ≠ μ
2
\item The pooled estimate of common variance σ2is
( 2)
( 1) ( 1)
1 2
2
2 2
2
2 1 1
+ −
− + −
=
n n
s n s n s p
=
12 15 2
11(0.85)2 14(0.98)2
+ −
+
= 0.8557
\item Hence, sp = 0.925
\item The test statistic is
1 2
1 2
1 1
| |
n n
s
t x x
p +
−
=
0.925 0.0833 0.0667
2.5
15
1
12
0.925 1
| 24.6 22.1|
+
=
+
−
=
0.3583
2.5
0.925(0.3873)
2.5
0.925 0.15
= 2.5 = = = 1.70874
\item The table value of t at 5\% level for 25 df is : 2.06
\item Reject H0.
\end{itemize}
\noindent \textbf{Part (c)}
c) The 95\% confidence interval for μ
1- μ
2 is ( )
1 2
1 2 / 2, 2
1 1
1 2 n n
x x t S
n n s − ± + α + −
= ( ) ⎥⎦
⎤
⎢⎣
⎡
− ± +
15
1
12
24.6 22.1 2.06(0.925) 1
=(-3.24,-1.76) or (1,76,3.24) for ( μ
2- μ
1 )
d) 95% confidence interval for 2
2
2
1 σ σ
(14,11) (14,11) 2 0.975
2
2
1
2
2
2
1
2 0.025
2
2
1 F
s
F s
s
s ≤ ≤
σ
σ
Substituting the values of 2
2
2
1 s , s and the table values, F0.025(14,11)=0.3205 and
F0.975(14,11)=3.43 we have the 95% CI as 0.3205(1/1.329) 3.43(1/1.329) 2
2
2
≤ 1 ≤
σ
σ
which results in { 0.2411 2.581 2
2
2
≤ 1 ≤
σ
σ
(use the fact that 0.3205
(11,14)
(14,11) 1
0.975
0.025 = =
F
F )

\end{document}
