%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

A study was done to find if the students who are good in high school, carry on to do well
also in the college. The high school grade (X) and college grade (Y) of 15 randomly
chosen students are given below.
S.No. 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
X 2.0 3.4 3.7 1.5 3.3 0.3 0.4 2.0 2.0 2.1 2.1 1.3 1.5 3.1 2.1
Y 2.0 2.6 3.8 1.1 3.0 0.1 1.4 1.5 1.4 4.0 1.5 1.3 1.9 3.1 1.9
(a) Draw a scatter plot of the above data with high school grades on X-axis and college
grades on Y-axis. 
(b) Estimate the slope and intercept parameters of the linear regression. Also calculate the
sample correlation coefficient between the high school grades and the college grades. 
(c) Can it be concluded that, in general, the expected performance in college is the same as
that in high school? 
(d) Estimate the college grade of a student who has a grade of 2.1 in high school. Comment
on the college grade of student number 10 in the above data.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\medskip 
\noindent \textbf{Solution}

a. The Scatter Plot
High school grade
0.0 .5 1.0 1.5 2.0 2.5 3.0 3.5 4.0
5
4
3
2
1
0
College grade
b. αˆ = 0.346 ;βˆ = 0.825;rˆ = 0.778;
c. As the estimate of the slope is lower than 1, the expected performance in college is lower
than the performance in high school.
d. yˆ =αˆ + βˆx = 0.346 + 0.825* 2.1 = 2.0785 .
Actual college grade for a high school grade of 2.1 for observation 10 is much higher
than the expected. This observation can be treated as an outlier while fitting the
regression.

\end{document}

To compute Sxx, Syy, and Sxy, you can use the following formulas:

**Sxx = Σ(xi - x̄)²**

**Syy = Σ(yi - ȳ)²**

**Sxy = Σ(xi - x̄)(yi - ȳ)**

where:

* xi and yi are the individual values of the x and y variables, respectively.
* x̄ and ȳ are the means of the x and y variables, respectively.
* Σ is the summation operator.

Here's the R code to calculate these values:

```R
# Create data frame with high school and college grades
data <- data.frame(
  X = c(2.0, 3.4, 3.7, 1.5, 3.3, 0.3, 0.4, 2.0, 2.0, 2.1, 2.1, 1.3, 1.5, 3.1, 2.1),
  Y = c(2.0, 2.6, 3.8, 1.1, 3.0, 0.1, 1.4, 1.5, 1.4, 4.0, 1.5, 1.3, 1.9, 3.1, 1.9)
)

# Calculate Sxx, Syy, and Sxy
x_bar <- mean(data$X)
y_bar <- mean(data$Y)

Sxx <- sum((data$X - x_bar)^2)
Syy <- sum((data$Y - y_bar)^2)
Sxy <- sum((data$X - x_bar) * (data$Y - y_bar))

# Print results
cat("Sxx:", Sxx, "\n")
cat("Syy:", Syy, "\n")
cat("Sxy:", Sxy, "\n")
```

This code will output the values of Sxx, Syy, and Sxy for the given data.

A study was done to find if the students who are good in high school, carry on to do well

also in the college. The high school grade (X) and college grade (Y) of 15 randomly

chosen students are given below.

S.No. 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15

X 2.0 3.4 3.7 1.5 3.3 0.3 0.4 2.0 2.0 2.1 2.1 1.3 1.5 3.1 2.1

Y 2.0 2.6 3.8 1.1 3.0 0.1 1.4 1.5 1.4 4.0 1.5 1.3 1.9 3.1 1.9

(a) Draw a scatter plot of the above data with high school grades on X-axis and college

grades on Y-axis. 

(b) Estimate the slope and intercept parameters of the linear regression. Also calculate the

sample correlation coefficient between the high school grades and the college grades. 

(c) Can it be concluded that, in general, the expected performance in college is the same as

that in high school? 

(d) Estimate the college grade of a student who has a grade of 2.1 in high school. Comment

on the college grade of student number 10 in the above data.

##############################```R
# Create data frame with high school and college grades
data <- data.frame(
  X = c(2.0, 3.4, 3.7, 1.5, 3.3, 0.3, 0.4, 2.0, 2.0, 2.1, 2.1, 1.3, 1.5, 3.1, 2.1),
  Y = c(2.0, 2.6, 3.8, 1.1, 3.0, 0.1, 1.4, 1.5, 1.4, 4.0, 1.5, 1.3, 1.9, 3.1, 1.9)
)

# Fit linear regression model
model <- lm(Y ~ X, data = data)

# Extract slope and intercept
slope <- coef(model)[2]
intercept <- coef(model)[1]

# Calculate correlation coefficient
correlation <- cor(data$X, data$Y)

# Print results
cat("Slope:", slope, "\n")
cat("Intercept:", intercept, "\n")
cat("Correlation coefficient:", correlation, "\n")
```

This code will output the estimated slope and intercept parameters of the linear regression model and the sample correlation coefficient between the high school grades and the college grades.
